package bear.game.company.environment;

public enum ActivityType {

    DECIDE_TO_ACCEPT_OTHER_ACTIVITY,
    BID_FOR_CONTRACT,
    RESEARCH,
    ADVERTISING_AND_SALES,
    CONTRACT_PRODUCT_DEVELOPMENT,
    HIRE_PERSON,
    PRODUCT_IMPROVEMENT;

}
